version: '3.4'
services:
  mongodb:
    container_name: mongodb
    image: mvertes/alpine-mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - tilda-mongo:/data/db
    expose: 
      - "27017"

  tilda-server:
    container_name: tilda-server
    restart: always
    build:
      context: ../mars-inventory-service
      dockerfile: Dockerfile-dev
    build: ./tilda-server
    depends_on: 
      - mongodb
    volumes:
      - ./tilda-server:/usr/app
      - ./tilda-server/static:/usr/app/static
    environment:
      - DB_URL=mongodb://mongodb:27017/tilda
      - ENV=development
      - APP_PORT='8080'
    expose:
      - "8080"

  tilda-client:
    container_name: tilda-client
    build: 
      context: ./tilda-client
      dockerfile: Dockerfile-dev
    depends_on:
      - tilda-server
    volumes:
      - ./tilda-client:/src/app
    expose:
      - "3000"

  tilda-bot:
    restart: always
    container_name: tilda-bot
    image: tilda-bot
    build: ./tilda-bot
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DB_URL=mongodb://mongodb:27017/tilda-bot
      - DB_ADAPTER=chatterbot.storage.MongoDatabaseAdapter
    volumes:
      - ./tilda-bot:/app
    expose:
      - "5000"

  proxy:
    build:
      context: ./proxy
      dockerfile: dev.Dockerfile
    container_name: nginx
    depends_on:
      - tilda-server
      - tilda-client
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/dev:/etc/nginx/conf.d/

volumes:
  tilda-mongo: