version: '2'
services:
  mongodb:
    container_name: mongodb
    mem_limit: 200m
    image: mvertes/alpine-mongo
    volumes:
      - tilda-mongo:/data/db
    ports:
      - '27017:27017'

  tilda-server:
    container_name: tilda-server
    mem_limit: 200m
    restart: always
    build: ./tilda-server
    depends_on: 
      - mongodb
    volumes:
      - ./tilda-server:/usr/app
      - ./tilda-server/static:/usr/app/static
    environment:
      - DB_URL=mongodb://mongodb:27017/tilda
      - ENV=development
      - APP_PORT='8080'
    ports:
      - '8080:8080'

  tilda-client:
    container_name: tilda-client
    mem_limit: 350m
    build: 
      context: ./tilda-client
      dockerfile: Dockerfile-dev
    depends_on:
      - tilda-server
    volumes:
      - ./tilda-client:/src/app
    ports:
      - '3000:3000'

  tilda-bot:
    restart: always
    container_name: tilda-bot
    image: tilda-bot
    build: ./tilda-bot
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DB_URL=mongodb://mongodb:27017/tilda-bot
      - DB_ADAPTER=chatterbot.storage.MongoDatabaseAdapter
    volumes:
      - "./tilda-bot:/app"
    ports:
      - '5000:5000'
    mem_limit: 300m


  proxy:
    build: ./proxy
    container_name: proxy
    mem_limit: 10m
    depends_on:
      - tilda-server
      - tilda-client
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy:/etc/nginx/conf.d/

volumes:
  tilda-mongo: