version: '3.4'
services:
  mongodb:
    container_name: mongodb
    image: mvertes/alpine-mongo
    volumes:
      - tilda-mongo:/data/db
    ports:
      - '27017:27017'

  tilda-server:
    container_name: tilda-server
    restart: always
    image: cloud.canister.io:5000/miun173/tilda-server:${TILDA_SERVER_VERSION}
    depends_on: 
      - mongodb
    volumes:
      - tilda-static:/usr/app/static
    environment:
      - DB_URL=mongodb://mongodb:27017/tilda
      - ENV=development
      - APP_PORT='8080'
    ports:
      - '8080:8080'

  tilda-client:
    container_name: tilda-client
    image: cloud.canister.io:5000/miun173/tilda-client:${TILDA_CLIENT_VERSION}
    depends_on:
      - tilda-server
    ports:
      - '3000:80'
    expose:
      - '80'

  tilda-bot:
    restart: always
    container_name: tilda-bot
    image: cloud.canister.io:5000/miun173/tilda-bot:${TILDA_BOT_VERSION}
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DB_URL=mongodb://mongodb:27017/tilda-bot
      - DB_ADAPTER=chatterbot.storage.MongoDatabaseAdapter
    ports:
      - '5000:5000'

  nginx:
    build: ./proxy
    container_name: nginx
    depends_on:
      - tilda-server
      - tilda-client
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy:/etc/nginx/conf.d/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: "journald"

volumes:
  tilda-mongo:
  tilda-static: